project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Quantifying Gendered Cost Burdens in Everyday Spending and Healthcare - Going Beyond the Pink Tax"
  author:
    - Sneha Jaikumar (sj3474)
    - Kaushiki Singh (ks4402)
  repo-url: https://github.com/snehajaikumar23/genderedCostBurdenAnalysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


